---
- hosts: all
  become: yes

  tasks:
  - name: Ensure Chrony is installed
    yum:
      name: chrony
      state: present

  - name: Ensure chrony is running
    service:
      name: chronyd
      enabled: yes

